name: Jatt

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./resume/resume.tex

      - name: Get Jatt
        run: |
          curl -LO "https://github.com/devmegablaster/jatt/releases/latest/download/jatt_Linux_x86_64.tar.gz"
          tar -xzf jatt_Linux_x86_64.tar.gz
          chmod +x jatt

      - name: Run Jatt
        run: ./jatt

      - name: Move Resume
        run: mv resume.pdf public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
